services:
  - type: web
    name: ayuraksha
    env: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      apt-get update && apt-get install -y tesseract-ocr && gunicorn app:app